name: Enforce Branch Creation Criteria

on:
  create:
    branches:
      - '*'

jobs:
  enforce_branch_creation_criteria:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch name
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          if [[ ! $branch_name =~ ^[0-9]+[a-zA-Z_-]+[0-9]+$ ]]; then
            echo "Invalid branch name. It should match the pattern: <issue number><feature name><sprint number>"
            exit 1
          fi


