name: Enforce Branch Naming

on:
  push:
    branches:
      - '*'

jobs:
  enforce_branch_naming:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enforce branch naming
        run: |
          branch_name=$(echo $GITHUB_REF | sed 's|.*/||')
          if [[ ! $branch_name =~ ^[0-9]+[a-zA-Z_-]+[0-9]+$ ]]; then
            echo "Invalid branch name. It should match the pattern: <issue number><feature name><sprint number>"
            exit 1
          fi


